### ISSUE TITLE
Unable to access en_us.zlib file over IIS

### ISSUE THREAD

**Issue by vaibhavseth** [gskinner/SPL#3]
I implemented SPL library in my Flex application, everything is working fine on my local machine(running the application from Flex Builder), but after deploying it to the test server,  I get 
Error #2044: Unhandled ioError:. text=Error #2032: Stream Error.
while loading the en_us.zlib.

I checked that the path of the zlib file is correct. When I go to the zlib path directly via browser I get "The page cannot be found" error.
Whereas, if I put an image file at the same location, I am able to access it via URL.

I checked the IIS settings as well, but don't see anything there as well which might be preventing it.

Any help will be really appreciated! Thanks!!

**Comment by lannymcnie** [comment]
It sounds like a mime type error. Try renaming the dictionary to .txt or .zip and see if that helps.

**Comment by wdamien** [comment]
You can also add custom mime types to IIS ... http://technet.microsoft.com/en-us/library/cc725608(v=ws.10).aspx might help.

**Comment by vaibhavseth** [comment]
Thanks for the quick response!
I came across another blog in the meantime as renamed the file to en_us.zlib-1.42.tar.gz and it worked.
I believe its related to mime types only, will check further to add the custom mime type to IIS.

Thanks again for your inputs.
