### ISSUE TITLE
Can't set SPLTag targetInstanceName through code

### ISSUE THREAD

**Issue by Surgery** [gskinner/SPL#4]
I'm trying to set up spell checking on a dynamically created TextField. I created a new SPLTag in my class, and used

splTag._targetInstanceName = textField.name;

I'm getting a null object reference error at that line though, and textField isn't null. Thanks.

**Comment by wdamien** [comment]
SPLTag is designed to be instantiated on stage. When using SPL in code just use SpellingHighlighter directly.

`new SpellingHighlighter(textField);`

**Comment by Surgery** [comment]
Thanks so much. I had a hell of a time finding examples using it in code.
