### ISSUE TITLE
SWCs for Flex 2.01

### ISSUE THREAD

**Issue by codemonkey81** [gskinner/SPL#7]
This is more of support than an issue, do you know where can i donwload the SWCs of SPL for Flex 2.01

**Comment by wdamien** [comment]
We don't officially support Flex 2.0, so unfortunately there are no pre-built swc's. I theory if you link directly to the source, enabling spelling using actionscript should work. I've never tested this so I can't guarantee it will work, but I can't think of any reason why it wouldn't.

**Comment by codemonkey81** [comment]
I haven't try that yet, i will try your suggestion, thanks so much for your reply.
