### ISSUE TITLE
Question regarding which dictionary is referenced for the spell check

### ISSUE THREAD

**Issue by amyharbert-wf** [gskinner/SPL#9]
Our client is inquiring about which dictionary (new oxford dictionary vs. cambridge dictionary, etc.?) is referenced for this spell check tool. Specifically they noted a discrepancy between non-cash and noncash. Our application (as well as this page I'm typing on) identifies "noncash" as misspelled. Where in Word noncash is not underlined red as misspelled. Please direct me to the correct channel for this information if this isn't the correct one. Thank you! ~Amy

**Comment by gskinner** [comment]
If I remember correctly (its been a few years), the wordlist is from an open sourced dictionary from the Open Office project. Unfortunately, I'm not sure where they sourced the list from.

You can edit the wordlist as well, if you find specific discrepancies.
